language: objective-c
os: osx
osx_image: xcode9

env:
  matrix:
    - TEST_TYPE=iOS

script:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace leetcode.xcodeproj -scheme leetcode -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -enableCodeCoverage YES | xcpretty
    fi
